### ISSUE TITLE
所用统计、业务处理非主流技术

### ISSUE THREAD

**Issue by pan2za** [iqiyi/qnsm#18]
建议尽快改道。愿意提供支持。

**Comment by phonehold** [comment]
> 建议尽快改道。愿意提供支持。

具体指的什么？安全小白。不太明白是哪些主流技术

**Comment by CosmosSun** [comment]
@pan2za 您好，能说明白是哪些主流技术么

**Comment by pan2za** [comment]
1 suricata可以，但suricata已经跑在dpdk了吗，并没有 
2 检测和报表aol的已有开源，这个架构使用的可接入各种ids/ips日志，架构更好
3 统计的kafka?试试时序数据库的接口
4 虚拟化还要做？试试fdio/vpp

**Comment by pan2za** [comment]
moloch，我老年痴呆，忘记名字了

**Comment by CosmosSun** [comment]
> 
> 
> 1 suricata可以，但suricata已经跑在dpdk了吗，并没有
> 2 检测和报表aol的已有开源，这个架构使用的可接入各种ids/ips日志，架构更好
> 3 统计的kafka?试试时序数据库的接口
> 4 虚拟化还要做？试试fdio/vpp

@pan2za 非常感谢
关于1，2两点
- qnsm针对suricata，增加了dpdk的收发包，并且集成进了流水线中
- 关于ids/ips日志接入工具选型这块，不在引擎的架构范围内，不过针对事件输出，增加了json格式的kafka输出

3，
时序数据库可能是更好的选择，谢谢

4.  虚拟化，现在不支持，在todo list中，有更详细点的建议么

**Comment by pan2za** [comment]
谢谢
