### ISSUE TITLE
请问下升级到５．０　需要修改哪些内容

### ISSUE THREAD

**Issue by gmctl** [iqiyi/qnsm#19]
因为我们现在用的规则集都是  suricata5.0 的　所以想了解下升级到最新版本需要修改哪些内容

**Comment by CosmosSun** [comment]
patch/suricata-4.1.0 目录是suricata修改的patch，5.0版本与4.1.0有差异，所以需要重新适配下

**Comment by aguaiyoung** [comment]
现在suricata 最新版本直接可以生成静态库了 libsuricata_c.a
