### ISSUE TITLE
编译IDPS lib失败

### ISSUE THREAD

**Issue by wangxiaodiao** [iqiyi/qnsm#20]
[root@localhost scripts]# sh build_idps.sh
正克隆到 '/opt/qnsm_deps'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
接收对象中:  76% (57078/74970), 33.77 MiB | 56.00 KiB/s

remote: Total 74970 (delta 0), reused 1 (delta 0), pack-reused 74964
接收对象中: 100% (74970/74970), 44.30 MiB | 36.00 KiB/s, done.
处理 delta 中: 100% (58996/58996), done.
build_idps.sh: 第 27 行:cd: /opt/qnsm_deps/suricata: 没有那个文件或目录
fatal: 引用不是一个树：787473ec64550a2448b81aa13064c1f613642c57
之前的变基目录 /opt/qnsm/.git/rebase-apply 仍然存在但给出了mbox。
正克隆到 'libhtp'...
remote: Enumerating objects: 10574, done.
remote: Total 10574 (delta 0), reused 0 (delta 0), pack-reused 10574
接收对象中: 100% (10574/10574), 10.13 MiB | 30.00 KiB/s, done.
处理 delta 中: 100% (6477/6477), done.
sh: autogen.sh: 没有那个文件或目录
build_idps.sh:行39: ./configure: 没有那个文件或目录
sed：无法读取 config.h：没有那个文件或目录
sed：无法读取 config.h：没有那个文件或目录
sed：无法读取 config.h：没有那个文件或目录
sed：无法读取 config.h：没有那个文件或目录
make: *** 没有指明目标并且找不到 makefile。 停止。
ERR: not found libsuri

**Comment by CosmosSun** [comment]
@wangxiaodiao 看着是clone suricata代码失败，是没有外网么

**Comment by mflu** [comment]
close it!
