### ISSUE TITLE
编译qnsm失败

### ISSUE THREAD

**Issue by wangxiaodiao** [iqiyi/qnsm#21]
qnsm_decode.c: 在函数‘qnsm_decode_vlan’中:
qnsm_decode.c:506:11: 警告：赋值时将指针赋给整数，未作类型转换 [默认启用]
     proto =(ntohs)vh->eth_proto;
           ^
qnsm_decode.c:506:19: 错误：expected ‘;’ before ‘vh’
     proto =(ntohs)vh->eth_proto;
                   ^
qnsm_decode.c:504:28: 警告：未使用的变量‘vh’ [-Wunused-variable]
     const struct vlan_hdr *vh = (const struct vlan_hdr *)pkt;

**Comment by CosmosSun** [comment]
> 
> 
> qnsm_decode.c: 在函数‘qnsm_decode_vlan’中:
> qnsm_decode.c:506:11: 警告：赋值时将指针赋给整数，未作类型转换 [默认启用]
> proto =(ntohs)vh->eth_proto;
> ^
> qnsm_decode.c:506:19: 错误：expected ‘;’ before ‘vh’
> proto =(ntohs)vh->eth_proto;
> ^
> qnsm_decode.c:504:28: 警告：未使用的变量‘vh’ [-Wunused-variable]
> const struct vlan_hdr *vh = (const struct vlan_hdr *)pkt;
@wangxiaodiao https://github.com/iqiyi/qnsm/pull/22 thks
