### ISSUE TITLE
启动失败，Cannot create CPU core mask

### ISSUE THREAD

**Issue by haol666** [iqiyi/qnsm#26]
[APP] Initializing CPU core map ...
PANIC in app_init_core_mask():
Cannot create CPU core mask
6: [./qnsm-inspect() [0x40f4fd]]
5: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f83faa4eb15]]
4: [./qnsm-inspect() [0x40f3c3]]
3: [./qnsm-inspect() [0x579a49]]
2: [./qnsm-inspect() [0x40d175]]
1: [./qnsm-inspect() [0x4dc66a]]
Aborted (core dumped)

**Comment by CosmosSun** [comment]
@haol666 您好，app_init_core_mask初始化core mask失败，可能是配置文件错误引起。
可以参考[配置手册](https://github.com/iqiyi/qnsm/blob/master/doc/configure-tutorial.md)。

绑核由以下配置的core项决定：
[PIPELINE12]
type = DUMP                             ; DUMP组件，dump DDOS攻击数据包并保存为pcap文件
**core** = s0c5                             ; Node 0 core 5 hyperthread 0
pktq_in = SWQ16 SWQ17 SWQ18 SWQ19 SWQ20 SWQ21 SWQ22 SWQ23 ; 收包软件队列
timer_period = 10

[PIPELINE17]
type = SIP_IN_AGG                       ; DDOS攻击源ip数据聚合并输出
**core** = s0c7h                            ; Node 0 core 7 hyperthread

**Comment by snoopy7713** [comment]
看配置手册没有看懂，如果一开始看懂了，也就不会出错了。
CPU现在是24个逻辑核

=========================================
Core and Socket Information (as reported by '/proc/cpuinfo')
=========================================

cores =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
sockets =  [0, 1]

        Socket 0        Socket 1        
        --------        --------        
Core 0  [0]             [12]            
Core 1  [1]             [13]            
Core 2  [2]             [14]            
Core 3  [3]             [15]            
Core 4  [4]             [16]            
Core 5  [5]             [17]            
Core 6  [6]             [18]            
Core 7  [7]             [19]            
Core 8  [8]             [20]            
Core 9  [9]             [21]            
Core 10 [10]            [22]            
Core 11 [11]            [23] 

48核心，需要3颗CPU

**Comment by snoopy7713** [comment]
QQ号：16200780 需要讨论一下，找不到讨论群
