### ISSUE TITLE
贵项目的DPDK版本升级到最新版可以吗？

### ISSUE THREAD

**Issue by bobzhangfw** [iqiyi/qnsm#28]
贵项目的DPDK版本升级到最新版可以吗？

**Comment by CosmosSun** [comment]
您好，可能会升级到DPDK 19.11.3 (LTS)版本，近期会做一个测试。

**Comment by bobzhangfw** [comment]
16.11.2能兼容redhat7.7吗？源码编译的时候，报错如下：
== Build lib/librte_eal/linuxapp/kni
  CC [M]  /opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.o
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在函数‘igb_ndo_bridge_getlink’中:
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2288:2: 错误：提供给函数‘ndo_dflt_bridge_getlink’的实参太少
  return ndo_dflt_bridge_getlink(skb, pid, seq, dev, mode, 0, 0, nlflags);
  ^
In file included from /usr/src/kernels/3.10.0-1062.el7.x86_64/include/net/gen_stats.h:6:0,
                 from /usr/src/kernels/3.10.0-1062.el7.x86_64/include/net/sch_generic.h:29,
                 from /usr/src/kernels/3.10.0-1062.el7.x86_64/include/linux/filter.h:14,
                 from /usr/src/kernels/3.10.0-1062.el7.x86_64/include/net/sock.h:67,
                 from /usr/src/kernels/3.10.0-1062.el7.x86_64/include/linux/tcp.h:23,
                 from /opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:34:
/usr/src/kernels/3.10.0-1062.el7.x86_64/include/linux/rtnetlink.h:125:12: 附注：在此声明
 extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
            ^
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在文件作用域：
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2309:2: 错误：初始值设定项里有未知的字段‘ndo_change_mtu’
  .ndo_change_mtu  = igb_change_mtu,
  ^
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2309:2: 错误：从不兼容的指针类型初始化 [-Werror]
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2309:2: 错误：(在‘igb_netdev_ops.ndo_validate_addr’的初始化附近) [-Werror]
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2317:2: 错误：初始值设定项里有未知的字段‘ndo_set_vf_vlan’
  .ndo_set_vf_vlan = igb_ndo_set_vf_vlan,
  ^
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: 在函数‘igb_ndo_bridge_getlink’中:
/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2296:1: 错误：在有返回值的函数中，控制流程到达函数尾 [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[10]: *** [/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.o] 错误 1
make[9]: *** [_module_/opt/qnsm_deps/dpdk-stable-16.11.2/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni] 错误 2
make[8]: *** [sub-make] 错误 2
make[7]: *** [rte_kni.ko] 错误 2
make[6]: *** [kni] 错误 2
make[5]: *** [linuxapp] 错误 2
make[4]: *** [librte_eal] 错误 2
make[3]: *** [lib] 错误 2
make[2]: *** [all] 错误 2
make[1]: *** [pre_install] 错误 2
make: *** [install] 错误 2

**Comment by CosmosSun** [comment]
http://patches.dpdk.org/patch/5799/
ndo_bridge_getlink has changed in kernel release 4.1. It adds new parameter which brakes compilation.
可以试试这个补丁

**Comment by bobzhangfw** [comment]
是要把linux的kernel升级到4.1吗？

**Comment by bobzhangfw** [comment]
您好，如果升级到5.8最新内核会怎么样呢？
