### ISSUE TITLE
能详细讲解下配置文件的使用吗？

### ISSUE THREAD

**Issue by bobzhangfw** [iqiyi/qnsm#29]
能详细讲解下qnsm_inspect.cfg配置文件的使用和各节点的作用吗？
编译完成，启动时报错：
[root@tcsoftserver qnsm]# ./qnsm-inspect -f qnsm_inspect.cfg -c . -p 3
[APP] Initializing CPU core map ...
[APP] CPU core mask = 0x00000000000000000000510045e77ffc
[APP] Initializing EAL ...
[APP] Initializing MEMPOOL0 ...
[APP] Initializing MEMPOOL1 ...
[APP] Initializing MEMPOOL2 ...
[APP] Initializing LINK0 (0) (4 RXQ, 0 TXQ) ...
PANIC in app_init_link():
LINK0 (0): init error (-22)
已放弃(吐核)

**Comment by CosmosSun** [comment]
可以参考https://github.com/iqiyi/qnsm/blob/master/doc/configure-tutorial.md，里面有详细描述

**Comment by snoopy7713** [comment]
想讨论qnsm的请联系俺QQ: 16200780 添加备注github qnsm
