### ISSUE TITLE
dpdk和网卡绑定后，两个网卡就找不到了。

### ISSUE THREAD

**Issue by bobzhangfw** [iqiyi/qnsm#30]
dpdk和网卡绑定后，两个网卡就找不到了。
这样的话，交换机的端口镜像怎么接入到服务器呢?

**Comment by bobzhangfw** [comment]
我有一台4个nic的服务器，em1作为业务口，和局域网连接，并建立内部网桥，给容器使用。
em2空闲
em3和em4与dpdk绑定。

**Comment by CosmosSun** [comment]
> 
> 
> dpdk和网卡绑定后，两个网卡就找不到了。
> 这样的话，交换机的端口镜像怎么接入到服务器呢?

- 网卡不再受linux系统管理，完全被dpdk接管（用户态pmd驱动）；基于dpdk的qnsm进程启动后，网卡状态up；
- 你的配置来说，镜像口和em3,em4网线、光纤连接即可。
