### ISSUE TITLE
编译安装IDPS lib编译失败

### ISSUE THREAD

**Issue by z19961225** [iqiyi/qnsm#32]
[root@localhost scripts]# sh build_idps.sh
fatal: destination path '/opt/qnsm_deps' already exists and is not an empty directory.
build_idps.sh: line 27: cd: /opt/qnsm_deps/suricata: No such file or directory
fatal: reference is not a tree: 787473ec64550a2448b81aa13064c1f613642c57
Applying: IDPS：make as a lib & support kafka
error: configure.ac: does not exist in index
error: src/Makefile.am: does not exist in index
error: src/decode.c: does not exist in index
error: src/decode.h: does not exist in index
error: src/output-json-alert.c: does not exist in index
error: src/output-json-http.c: does not exist in index
error: src/output-json-http.h: does not exist in index
error: src/output-json.c: does not exist in index
error: src/runmodes.c: does not exist in index
error: src/runmodes.h: does not exist in index
error: src/tm-modules.c: does not exist in index
error: src/tm-threads-common.h: does not exist in index
error: src/util-error.c: does not exist in index
error: src/util-error.h: does not exist in index
error: src/util-logopenfile.c: does not exist in index
error: src/util-logopenfile.h: does not exist in index
Patch failed at 0001 IDPS：make as a lib & support kafka
The copy of the patch that failed is found in:
   /opt/qnsm/.git/rebase-apply/patch
When you have resolved this problem, run "git am --resolved".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Cloning into 'libhtp'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 10631 (delta 29), reused 38 (delta 20), pack-reused 10577
Receiving objects: 100% (10631/10631), 10.21 MiB | 121.00 KiB/s, done.
Resolving deltas: 100% (6509/6509), done.
sh: autogen.sh: No such file or directory
build_idps.sh: line 39: ./configure: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
ERR: not found libsuri
[root@localhost scripts]# ls

**Comment by Mikewyf** [comment]
build_idps.sh脚本第25行改成
git clone $SURICATA_URL $DEP_PATH/suricata
应该能解决这个问题

**Comment by z19961225** [comment]
改变了25行，但是还是报错

[root@localhost scripts]# sh build_idps.sh
Cloning into '/opt/qnsm_deps/suricata'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 80830 (delta 35), reused 46 (delta 30), pack-reused 80774
Receiving objects: 100% (80830/80830), 48.03 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (63706/63706), done.
Note: checking out '787473ec64550a2448b81aa13064c1f613642c57'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 787473e... changelog: update for 4.1
Applying: IDPS：make as a lib & support kafka
Cloning into 'libhtp'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 10631 (delta 29), reused 38 (delta 20), pack-reused 10577
Receiving objects: 100% (10631/10631), 10.21 MiB | 453.00 KiB/s, done.
Resolving deltas: 100% (6509/6509), done.
which: no libtoolize in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
which: no glibtoolize in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Failed to find libtoolize or glibtoolize, please ensure it is installed and accessible via your PATH env variable
build_idps.sh: line 39: ./configure: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
sed: can't read config.h: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
ERR: not found libsuri

**Comment by z19961225** [comment]
之前我编译安装DPDK的时候，遇到了错误：提供给函数‘ndo_dflt_bridge_getlink’的实参太少，
然后通过修改dpdk文件夹/x86_64-native-linuxapp-gcc/.config文件里的
CONFIG_RTE_LIBRTE_KNI=n
CONFIG_RTE_KNI_KMOD=n
才通过了编译

**Comment by z19961225** [comment]
会不会是这个影响了

**Comment by CosmosSun** [comment]
> 
> 
> 会不会是这个影响了

编译IDPS lib和编译dpdk没有关系的

**Comment by CosmosSun** [comment]
> 
> 
> > 会不会是这个影响了
> 
> 编译IDPS lib和编译dpdk没有关系的
which: no libtoolize in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
which: no glibtoolize in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Failed to find libtoolize or glibtoolize, please ensure it is installed and accessible via your PATH env variable

**Comment by z19961225** [comment]
记录一下，缺少libtool
yum install -y libtool

**Comment by z19961225** [comment]
现在在编译QNSM的时候又卡住了....
[root@localhost scripts]# sh build_qnsm_lib.sh 
build qnsm lib
Configuration done
Conflict: local config and template config have both changed
make[1]: *** [pre_install] Error 1
make: *** [install] Error 2

**Comment by z19961225** [comment]
具体报错如下
[root@localhost dpdk-stable-16.11.2]# make install x86_64-native-linuxapp-gcc
make[1]: Nothing to be done for `pre_install'.
/opt/qnsm_deps/dpdk-stable-16.11.2/mk/rte.vars.mk:61: build/.config: No such file or directory
/opt/qnsm_deps/dpdk-stable-16.11.2/mk/rte.vars.mk:84: *** RTE_ARCH is not defined.  Stop.
make: *** [install] Error 2

**Comment by CosmosSun** [comment]
您好，RTE_ARCH 和RTE_SDK是dpdk相关的环境变量，文档里面有相关说明；
还是建议按照readme文档操作

**Comment by snoopy7713** [comment]
想讨论qnsm的请联系俺QQ: 16200780 添加备注github qnsm
