### ISSUE TITLE
DPI 支持的有些问题，后续有新版本嘛？

### ISSUE THREAD

**Issue by wuningbo** [iqiyi/qnsm#34]

**Comment by mflu** [comment]
能方便具体描述一下问题么?

**Comment by wuningbo** [comment]
比如我要 请求dns&nbsp; 服务 ip是8.8.8.8 ，然后统计会话的日志 正反向方向就会反， 因为 那个接口判断的有问题。http 协议解析 只会拿第一个包的payload匹配，不会更新 新的payload 去识别

**Comment by CosmosSun** [comment]
> 比如我要 请求dns&nbsp; 服务 ip是8.8.8.8 ，然后统计会话的日志 正反向方向就会反， 因为 那个接口判断的有问题。http 协议解析 只会拿第一个包的payload匹配，不会更新 新的payload 去识别

您好，qnsm本身的dpi能力目前相对简单，dns的问题能提一个详细issue么；在流重组后，会对每个http payload识别的

**Comment by wuningbo** [comment]
嗯，不是dns 问题， 就是拿五元组算哈希以及判断方向存在问题，比如我的内网ip 访问 外网的ip 是8.8.8.8 后， 最后flow的日志正反向全部是反的。

**Comment by CosmosSun** [comment]
> 
> 嗯，不是dns 问题， 就是拿五元组算哈希以及判断方向存在问题，比如我的内网ip 访问 外网的ip 是8.8.8.8 后， 最后flow的日志正反向全部是反的。

目前QNSM DPI**没有去标识server和client端**，主要是以下原因：
- 有些环境只镜像了单向流
- http可以req、resp分别输出，也可以合并成一条数据输出
- 其他应用层协议，双向分别输出
- 传输层session的五元组key是按照ip+port升序生成的（qnsm_sess_generate_key），与方向无关，因而会出现用session key判断方向失效的问题

您是打开了qnsm_sessm.xml的dns proto的parse配置么，我记得是默认关闭的

**Comment by wuningbo** [comment]
哦哦， 明白了。 我是把 dns 打开了， 只跑dpi了。&nbsp; 咱们现在有新的开发版本么， 能否给一个版本呢

**Comment by CosmosSun** [comment]
> 
> 哦哦， 明白了。 我是把 dns 打开了， 只跑dpi了。&nbsp; 咱们现在有新的开发版本么， 能否给一个版本呢

节后可以解决这个问题，谢谢

**Comment by wuningbo** [comment]
好的， 感谢。。

**Comment by wuningbo** [comment]
方便加个微信嘛， 还有几个问题。

**Comment by Mikewyf** [comment]
> > 比如我要 请求dns  服务 ip是8.8.8.8 ，然后统计会话的日志 正反向方向就会反， 因为 那个接口判断的有问题。http 协议解析 只会拿第一个包的payload匹配，不会更新 新的payload 去识别
> 
> 您好，qnsm本身的dpi能力目前相对简单，dns的问题能提一个详细issue么；在流重组后，会对每个http payload识别的

tcp的流重组是通过tcp_data_proc()完成的吗？我在运行时发现，当识别到http后，只会记录第一个包的payload长度，同session后续包的处理都会按照这个payload执行，并且看起来处理的并不是重组后的包。假如第一个进入到http_classify()的包payload长度是0，那么后续所有包都会按payload是0处理（remaining始终是0），导致完全没有解析http消息。打印出的日志如下：
```
[QNSM]http_classify:145 enter
[QNSM]http_classify:212 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
[QNSM]http_parse:227 enter
[QNSM]http_parse:301 leave
```

**Comment by wuningbo** [comment]
> > > 比如我要 请求dns  服务 ip是8.8.8.8 ，然后统计会话的日志 正反向方向就会反， 因为 那个接口判断的有问题。http 协议解析 只会拿第一个包的payload匹配，不会更新 新的payload 去识别
> > 
> > 
> > 您好，qnsm本身的dpi能力目前相对简单，dns的问题能提一个详细issue么；在流重组后，会对每个http payload识别的
> 
> tcp的流重组是通过tcp_data_proc()完成的吗？我在运行时发现，当识别到http后，只会记录第一个包的payload长度，同session后续包的处理都会按照这个payload执行，并且看起来处理的并不是重组后的包。假如第一个进入到http_classify()的包payload长度是0，那么后续所有包都会按payload是0处理（remaining始终是0），导致完全没有解析http消息。打印出的日志如下：
> 
> ```
> [QNSM]http_classify:145 enter
> [QNSM]http_classify:212 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> ```

是的， 这是一个bug。

**Comment by CosmosSun** [comment]
> 
> 
> > > 比如我要 请求dns  服务 ip是8.8.8.8 ，然后统计会话的日志 正反向方向就会反， 因为 那个接口判断的有问题。http 协议解析 只会拿第一个包的payload匹配，不会更新 新的payload 去识别
> > 
> > 
> > 您好，qnsm本身的dpi能力目前相对简单，dns的问题能提一个详细issue么；在流重组后，会对每个http payload识别的
> 
> tcp的流重组是通过tcp_data_proc()完成的吗？我在运行时发现，当识别到http后，只会记录第一个包的payload长度，同session后续包的处理都会按照这个payload执行，并且看起来处理的并不是重组后的包。假如第一个进入到http_classify()的包payload长度是0，那么后续所有包都会按payload是0处理（remaining始终是0），导致完全没有解析http消息。打印出的日志如下：
> 
> ```
> [QNSM]http_classify:145 enter
> [QNSM]http_classify:212 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> [QNSM]http_parse:227 enter
> [QNSM]http_parse:301 leave
> ```

- 流重组是tcp_data_proc完成的；
- http parse 只使用第一个包长度是一个bug，thks @wuningbo
- 您是如何打开DPI的？从代码看需要打开qnsm_session.xml中的dpi配置并且在config中文件配置__QNSM_STREAM_REASSEMBLE，并且发生攻击事件的时候cmd msg才会触发

**Comment by wuningbo** [comment]
我修改配置文件，然后修改makefile了。 就为了跑dpi

**Comment by CosmosSun** [comment]
嗯嗯，DPI这块可能需要改进，非常感谢

**Comment by Mikewyf** [comment]
> 我修改配置文件，然后修改makefile了。 就为了跑dpi

我也是这样跑的。
还有一个问题，是tcp_data_proc在进行流重组时，每收到一个包，都会把它当作第一个包存入链表，并对这个包进行应用层协议的解析（我是用http测试的），然后这个包就被free掉了。再收到一个包时，又会按照第一个包的方式直接存入链表并解析、free，这样的话好像并不是一个先重组还原完整包，再解析的过程吧？

**Comment by wuningbo** [comment]
我还发现了一些其他问题 可否加个联系方式，方便探讨

**Comment by CosmosSun** [comment]
> 
> 我还发现了一些其他问题 可否加个联系方式，方便探讨

有一个对外的邮件组qnsm_devel#qiyi.com (请用@替换#). 目前还没有使用IM

**Comment by CosmosSun** [comment]
>  还有一个问题，是tcp_data_proc在进行流重组时，每收到一个包，都会把它当作第一个包存入链表，并对这个包进行应用层协议的解析（我是用http测试的），然后这个包就被free掉了。再收到一个包时，又会按照第一个包的方式直接存入链表并解析、free，这样的话好像并不是一个先重组还原完整包，再解析的过程吧？

您好，确实没有完整还原包，按照tcp seq做了排序，一方面完整还原包的话，需要多一次复制，另外设计之初侧重点还是DDoS检测，并在此基础上支持一定的应用层DPI能力，特别是http协议parse是有状态的，也没有必要还原完整包；后续集成了Suricata IDPS，Suricata的dpi更丰富，配置也更灵活；

**Comment by Mikewyf** [comment]
> 我还发现了一些其他问题 可否加个联系方式，方便探讨

还有哪些问题呢，咱们可以交流一下

**Comment by wuningbo** [comment]
q q : 398596884

**Comment by mflu** [comment]
> 我还发现了一些其他问题 可否加个联系方式，方便探讨

我们不顾虑私聊, 建议在github提交issue进行讨论,共同推动QNSM变得更好, 也让其他QNSM的用户受益

**Comment by wuningbo** [comment]
好的， 针对年前说的问题， 希望年后能有一个版本 试试

**Comment by cfrchj** [comment]
终于更新了，快，等了这么久，十分迫切

**Comment by mflu** [comment]
fixed in https://github.com/iqiyi/qnsm/pull/36 & merged.

Close it!

**Comment by snoopy7713** [comment]
想讨论qnsm的请联系俺QQ: 16200780 添加备注github qnsm
