### ISSUE TITLE
http.log和log.pcap数据日志有丢失的问题请教

### ISSUE THREAD

**Issue by wuhuisong** [iqiyi/qnsm#41]
我同时用10个线程发起HTTP请求，每个线程进行10次，共100个http请求，但/var/log/suricata/的http.log和log.pcap显示只有80多个左右的请求（用1个线程发起10个HTTP请求，http.log和log.pcap也经常有数据丢失），请问一般是什么问题引起的？还是我配置有问题？请指教，非常感谢！
我的CPU配置如下：
![微信截图_20210807212636](https://user-images.githubusercontent.com/57657847/128601771-bfed65ab-c595-45f7-b84c-deb54d0874dc.png)

qnsm_inspect.cfg配置如下
`[EAL]
log_level = 8
n = 1
socket_mem = 2048
master_lcore = 0

[IDPS]
conf_file = ./suricata.yaml

;mbuf mempool cfg
;add mbuf priavte size para
[MEMPOOL0]
buffer_size = 2304
pool_size = 65536
cache_size = 256
cpu = 0
private_size = 64

[MEMPOOL1]
buffer_size = 2304
pool_size = 65536
cache_size = 256
cpu = 0
private_size = 64 

[MEMPOOL2]
buffer_size = 2304
pool_size = 65536
cache_size = 256
cpu = 0
private_size = 64 

;link cfg
[LINK0]
rss_qs = 0 1 2 3 4 5
rss_proto_ipv4 = TCP UDP
rss_proto_ipv6 = TCP TCP_EX UDP UDP_EX
symmetrical_rss = yes
;ip_local_q = 7  reserved for future proto stack app
;arp_q = 8

;rx queue cfg
;http://dpdk.org/doc/guides/nics/ixgbe.html

[RXQ0.0]
size = 2048
burst = 64

[RXQ0.1]
size = 2048
burst = 64

[RXQ0.2]
size = 2048
burst = 64

[RXQ0.3]
size = 2048
burst = 64

[RXQ0.4]
size = 2048
burst = 64

[RXQ0.5]
size = 2048
burst = 64

[SWQ0]
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ1]
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ2]
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ3]
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ4]
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ5]
size = 2048
cpu = 0
mempool = MEMPOOL1
dump = yes

[SWQ6]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

[SWQ7]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

[SWQ8]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

[SWQ9]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

[SWQ10]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

[SWQ11]
size = 2048
cpu = 0
mempool = MEMPOOL2
dup = yes

;app cfg
[PIPELINE0]
type = MASTER
core = s0c0;lcore24

[PIPELINE1]
type = SESSM
core = s0c0
pktq_in = RXQ0.0
pktq_out = SWQ0 SWQ6 SWQ12
timer_period = 10

[PIPELINE2]
type = SESSM
core = s0c1
pktq_in = RXQ0.1
pktq_out = SWQ1 SWQ7 SWQ13
timer_period = 10

[PIPELINE3]
type = SESSM
core = s0c2
pktq_in = RXQ0.2
pktq_out = SWQ2 SWQ8 SWQ14
timer_period = 10

[PIPELINE4]
type = SESSM
core = s0c3
pktq_in = RXQ0.3
pktq_out = SWQ3 SWQ9 SWQ15
timer_period = 10

[PIPELINE5]
type = SESSM
core = s0c4
pktq_in = RXQ0.4
pktq_out = SWQ4 SWQ10 SWQ16
timer_period = 10

[PIPELINE6]
type = SESSM
core = s0c5
pktq_in = RXQ0.5
pktq_out = SWQ5 SWQ11 SWQ17
timer_period = 10

[PIPELINE7]
type = DUMP
core = s0c5
pktq_in = SWQ0 SWQ1 SWQ2 SWQ3 SWQ4 SWQ5
timer_period = 10

[PIPELINE8]
type = SIP_IN_AGG
core = s0c5

[PIPELINE9]
type = VIP_AGG
core = s0c5
pktq_in = SWQ12 SWQ13 SWQ14 SWQ15 SWQ16 SWQ17
timer_period = 10

[PIPELINE10]
type = EDGE
core = s0c4

;IPS BEGIN
[PIPELINE11]
type = DETECT
core = s0c0
pktq_in = SWQ6

[PIPELINE12]
type = DETECT
core = s0c1
pktq_in = SWQ7

[PIPELINE13]
type = DETECT
core = s0c2
pktq_in = SWQ8

[PIPELINE14]
type = DETECT
core = s0c3
pktq_in = SWQ9

[PIPELINE15]
type = DETECT
core = s0c4
pktq_in = SWQ10

[PIPELINE16]
type = DETECT
core = s0c5
pktq_in = SWQ11
;IPS END
`

**Comment by wuhuisong** [comment]
问题已解决，原因是VIP_AGG漏写了两段，需加全
[PIPELINE10]
type = VIP_AGG
core = s0c5
pktq_in = SWQ0 SWQ1 SWQ2 SWQ3 SWQ4 SWQ5
timer_period = 10
[PIPELINE11]
type = VIP_AGG
core = s0c5
pktq_in = SWQ6 SWQ7 SWQ8 SWQ9 SWQ10 SWQ11
timer_period = 10

**Comment by snoopy7713** [comment]
想讨论qnsm的请联系俺QQ: 16200780 添加备注github qnsm
